name: CI/CD
on: [push, pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source-code
        uses: actions/checkout@v2
      - name: Setup (NIXPKGS_COMMIT)
        run: echo "NIXPKGS_COMMIT=$(curl -L 'https://channels.nixos.org/nixos-unstable/git-revision')" >> $GITHUB_ENV
      - name: Install Nix
        uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/${{ env.NIXPKGS_COMMIT }}.tar.gz
      - name: Build the Anfiheft
        run: |
          .github/scripts/gen-buildinfo.sh
          nix-build --argstr date "$(date --date=@$(git log -1 --pretty=%ct) +%F)"
          mkdir anfiheft && cp result/* .BUILDINFO anfiheft/
      - name: Upload the Anfiheft (GitHub artifacts)
        uses: actions/upload-artifact@v2
        with:
          name: anfiheft
          path: anfiheft/
      - name: Deploy the Anfiheft
        if: ${{ github.repository_owner == 'fsi-tue' && github.ref == 'refs/heads/master' }}
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: .github/scripts/deploy.sh
